version: '2'
services:
  database:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      POSTGRES_USER: "myapp"
      POSTGRES_PASSWORD: "dbpass"
      POSTGRES_DB:       "myapp"
  configserver:
    extends:
      file: ../common/docker-compose.yml
      service: configserver
  licensingservice:
     image: ch3-thoughtmechanix/licensing-service
     ports:
       - "8080:8080"
     environment:
       PROFILE: "dev"
       CONFIGSERVER_URI: "http://configserver:8888"
       CONFIGSERVER_PORT:   "8888"
       DATABASESERVER_PORT: "15432"
