server:
  port: 8888
spring:
 profiles:
    active: native
 cloud:
   config:
     server:
       native:
         search-locations: file:///home/wz/workspaces/spmia-cloud-config-server/src/main/resources/config/licensingservice